### ISSUE TITLE
Error with eslint 4.11.0 (Latest)

### ISSUE THREAD

**Issue by adaje41** [forcedotcom/eslint-plugin-visualforce#1]
I'm getting this error when trying to run eslint v4.11.0

Plugin works if I downgrade to the last 3.x version.

`Cannot read property 'exports' of undefined
TypeError: Cannot read property 'exports' of undefined
    at patchESLint (C:\Users\600119087\AppData\Roaming\npm\node_modules\@salesforce\eslint-plugin-visualforce\dist\index.js:840:41)
    at Object.<anonymous> (C:\Users\600119087\AppData\Roaming\npm\node_modules\@salesforce\eslint-plugin-visualforce\dist\index.js:980:1)
    at __webpack_require__ (C:\Users\600119087\AppData\Roaming\npm\node_modules\@salesforce\eslint-plugin-visualforce\dist\index.js:21:30)
    at Object.<anonymous> (C:\Users\600119087\AppData\Roaming\npm\node_modules\@salesforce\eslint-plugin-visualforce\dist\index.js:1681:18)
    at __webpack_require__ (C:\Users\600119087\AppData\Roaming\npm\node_modules\@salesforce\eslint-plugin-visualforce\dist\index.js:21:30)
    at module.exports.Op (C:\Users\600119087\AppData\Roaming\npm\node_modules\@salesforce\eslint-plugin-visualforce\dist\index.js:67:18)
    at Object.<anonymous> (C:\Users\600119087\AppData\Roaming\npm\node_modules\@salesforce\eslint-plugin-visualforce\dist\index.js:70:10)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)`

**Comment by touzoku** [comment]
Hi, this module is not compatible with eslint 4, it is work in progress still. Please keep updated.
